[package]
name = "yrifl/lit"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies] # My custom libs, you can edit.
Cmdr = "evaera/cmdr@1.9.0"
Promise = "evaera/promise@4.0.0"
testez = "roblox/testez@0.4.1"
Janitor = "howmanysmall/janitor@1.15.1"
Roact = "roblox/roact@1.4.4"
BridgeNet2 = "ffrostflame/bridgenet2@0.1.0"

# Sleitnick's framework
Knit = "sleitnick/knit@1.4.7"

# Sleitnick's libs https://sleitnick.github.io/RbxUtil/
Streamable = "sleitnick/streamable@1.2.4"
Component = "sleitnick/component@2.4.6"
TableUtil = "sleitnick/table-util@1.2.0"
PID = "sleitnick/pid@1.0.2"
Signal = "sleitnick/signal@1.4.2"
Option = "sleitnick/option@1.0.4"
Concur = "sleitnick/concur@0.1.2"
Log = "sleitnick/log@0.1.1"
EnumList = "sleitnick/enum-list@2.0.1"
TaskQueue = "sleitnick/task-queue@0.1.1"
Timer = "sleitnick/timer@1.1.2"
Symbol = "sleitnick/symbol@2.0.1"
